=== Latepate64/duel-zone/Models/Cards.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="Cards"
  xmlns:abi="Abilities"
  xmlns:ta="TriggeredAbilities"
  xmlns:aa="ActivatedAbilities"
  xmlns:sa="StaticAbilities"
  xmlns:ra="Races"
  targetNamespace="Cards"
  elementFormDefault="qualified"
>
  <xs:import
    namespace="Abilities"
    schemaLocation="Abilities.xsd"
  />
  <xs:import
    namespace="TriggeredAbilities"
    schemaLocation="TriggeredAbilities.xsd"
  />
  <xs:import
    namespace="ActivatedAbilities"
    schemaLocation="ActivatedAbilities.xsd"
  />
  <xs:import
    namespace="StaticAbilities"
    schemaLocation="StaticAbilities.xsd"
  />
  <xs:import
    namespace="Races"
    schemaLocation="Races.xsd"
  />
  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cards">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded">
              <xs:element type="Creature" name="Creature" />
              <xs:element type="EvolutionCreature" name="EvolutionCreature" />
              <xs:element type="Spell" name="Spell" />
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Card" abstract="true">
    <xs:sequence>
      <xs:element name="Civilizations">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Civilization" type="Civilization" minOccurs="1" maxOccurs="5" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Cost" type="xs:int" use="required" />
  </xs:complexType>
  <xs:complexType name="Creature">
    <xs:complexContent>
      <xs:extension base="Card">
        <xs:sequence>
          <xs:element name="Races">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Race" type="ra:Race" minOccurs="1" maxOccurs="2" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Abilities">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element type="ta:WhenYouPutThisCreatureIntoTheBattleZoneAbility"
                  name="WhenYouPutThisCreatureIntoTheBattleZoneAbility" />
                <xs:element type="aa:TapAbility" name="TapAbility" />
                <xs:element type="sa:BlockerAbility" name="BlockerAbility" />
                <xs:element type="sa:ShieldTriggerAbility" name="ShieldTriggerAbility" />
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="Power" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EvolutionCreature">
    <xs:complexContent>
      <xs:extension base="Creature"/>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Spell">
    <xs:complexContent>
      <xs:extension base="Card">
        <xs:sequence>
          <xs:element name="Abilities">
            <xs:complexType>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element type="abi:SpellAbility" name="SpellAbility"></xs:element>
                <xs:element type="sa:ShieldTriggerAbility" name="ShieldTriggerAbility" />
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="Civilization">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Light" />
      <xs:enumeration value="Water" />
      <xs:enumeration value="Darkness" />
      <xs:enumeration value="Fire" />
      <xs:enumeration value="Nature" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Latepate64/duel-zone/Server/cards.xml
<?xml version="1.0"?>
<Root
    xmlns="Cards"
    xmlns:abi="Abilities"
    xmlns:ose="OneShotEffects"
    xmlns:cf="CardFilters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="Cards ../Models/Cards.xsd
                        Abilities ../Models/Abilities.xsd
                        OneShotEffects ../Models/OneShotEffects.xsd
                        Races ../Models/Races.xsd
                        CardFilters ../Models/CardFilters.xsd"
>
    <Cards>
        <Creature Name="Burning Mane" Cost="2" Power="2000">
            <Civilizations>
                <Civilization>Nature</Civilization>
            </Civilizations>
            <Races>
                <Race>Beast Folk</Race>
            </Races>
            <Abilities />
        </Creature>
        <Spell Name="Holy Awe" Cost="6">
            <Civilizations>
                <Civilization>Light</Civilization>
            </Civilizations>
            <Abilities>
                <SpellAbility>
                    <abi:TapAllYourOpponentsCreaturesEffect>
                        <ose:CreatureFilter />
                    </abi:TapAllYourOpponentsCreaturesEffect>
                </SpellAbility>
            </Abilities>
        </Spell>
        <Creature Name="Immortal Baron, Vorg" Cost="2" Power="2000">
            <Civilizations>
                <Civilization>Fire</Civilization>
            </Civilizations>
            <Races>
                <Race>Human</Race>
            </Races>
            <Abilities />
        </Creature>
        <Spell Name="Terror Pit" Cost="6">
            <Civilizations>
                <Civilization>Darkness</Civilization>
            </Civilizations>
            <Abilities>
                <SpellAbility>
                    <abi:DestroyOneOfYourOpponentsCreaturesEffect />
                </SpellAbility>
            </Abilities>
        </Spell>
        <Creature Name="Aqua Hulcus" Cost="3" Power="2000">
            <Civilizations>
                <Civilization>Water</Civilization>
            </Civilizations>
            <Races>
                <Race>Liquid People</Race>
            </Races>
            <Abilities>
                <WhenYouPutThisCreatureIntoTheBattleZoneAbility>
                    <abi:YouMayDrawCardEffect />
                </WhenYouPutThisCreatureIntoTheBattleZoneAbility>
            </Abilities>
        </Creature>
        <Creature Name="Rikabu's Screwdriver" Cost="2" Power="1000">
            <Civilizations>
                <Civilization>Fire</Civilization>
            </Civilizations>
            <Races>
                <Race>Xenoparts</Race>
            </Races>
            <Abilities>
                <TapAbility>
                    <abi:DestroyOneOfYourOpponentsCreaturesThatHasBlockerEffect />
                </TapAbility>
            </Abilities>
        </Creature>
        <Creature Name="King Coral" Cost="3" Power="1000">
            <Civilizations>
                <Civilization>Water</Civilization>
            </Civilizations>
            <Races>
                <Race>Leviathan</Race>
            </Races>
            <Abilities>
                <BlockerAbility />
            </Abilities>
        </Creature>
        <Creature Name="Gonta, the Warrior Savage" Cost="2" Power="4000">
            <Civilizations>
                <Civilization>Fire</Civilization>
                <Civilization>Nature</Civilization>
            </Civilizations>
            <Races>
                <Race>Human</Race>
                <Race>Beast Folk</Race>
            </Races>
            <Abilities />
        </Creature>
        <EvolutionCreature Power="5000" Name="Larba Geer, the Immaculate" Cost="3">
            <Civilizations>
                <Civilization>Light</Civilization>
            </Civilizations>
            <Races>
                <Race>Guardian</Race>
            </Races>
            <Abilities>
                <WhenYouPutThisCreatureIntoTheBattleZoneAbility>
                    <abi:TapAllYourOpponentsCreaturesEffect>
                        <ose:BlockerFilter />
                    </abi:TapAllYourOpponentsCreaturesEffect>
                </WhenYouPutThisCreatureIntoTheBattleZoneAbility>
            </Abilities>
        </EvolutionCreature>
    </Cards>
</Root>
